/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userdemo;

import com.user.Model.books;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import registeruser.dbconnection.DBConnection;

/**
 *
 * @author Pasan
 */
public final class DisplayENGnovels extends javax.swing.JFrame {
        public DisplayENGnovels() {
            initComponents();
            showBooks_in_jtable();
            setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    

        public ArrayList<books> userbookList(){
            
            ArrayList<books> booklist = new ArrayList<books>();
            Connection connection = DBConnection.createConnection();
            String query = "SELECT * FROM enovels";
            Statement st;
            ResultSet rs;
            
            
            try{
                st = connection.createStatement();
                rs = st.executeQuery(query);
                books b1;
                while(rs.next()){
                    b1 = new books(rs.getInt("eid"),rs.getString("ename"),rs.getString("eauthor"),rs.getDouble("eprice"));
                    booklist.add(b1);
                }
                
            }catch(Exception e){
                
                e.printStackTrace();
                
            }   
            return booklist;
       
        }
        
        public double calculateTotal(){  
            double total =0;
            for (int i = 0; i < jTable_display_books.getRowCount(); i++){
                //int amount = Integer.parseInt((String)jTable_display_books.getValueAt(i, 4));
                //int amount = Integer.parseInt(jTable_display_books.getValueAt(i, 3)+"");
                //total += amount;
                total = total+Double.parseDouble(jTable_display_books.getValueAt(i, 3).toString());
            }
            return total;
        }
        public void showBooks_in_jtable(){
            ArrayList<books> list = userbookList();
            
            DefaultTableModel model = (DefaultTableModel) jTable_display_books.getModel();
            Object [] row = new Object[4];
            for(int i =0;i<list.size();i++){
                row[0] = list.get(i).getId();
                row[1] = list.get(i).getName();
                row[2] = list.get(i).getAuthor();
                row[3] = list.get(i).getprice();     
                
                model.addRow(row);
            }
            
            
        }
        public int engcountRows() throws SQLException{
            Connection connection = DBConnection.createConnection();
            String query = "SELECT * FROM enovels";
            Statement st;
            ResultSet rs;
            st = connection.createStatement();
            rs = st.executeQuery(query);
            
            int count =0;
            while(rs.next()){
                count ++;
            }
            return count;
        }

         public void executeQuery(String query,String message){
            
            Connection connection = DBConnection.createConnection();
            Statement st;
            try{
                st = connection.createStatement();
                if((st.executeUpdate(query)) == 1){
                    DefaultTableModel model = (DefaultTableModel) jTable_display_books.getModel();
                    model.setRowCount(0);
                    showBooks_in_jtable();
                    JOptionPane.showMessageDialog(null,"Data  "+message+"succesfullly");
                    
                }
                else{
                     JOptionPane.showMessageDialog(null,"Data not "+message);
                }
                
                
            }catch(Exception ex){
                
                ex.printStackTrace();
                
            }

            
            
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        eauthor = new javax.swing.JTextField();
        eid = new javax.swing.JTextField();
        eprice = new javax.swing.JTextField();
        ename = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_display_books = new javax.swing.JTable();
        delete = new javax.swing.JButton();
        totalprice = new javax.swing.JButton();
        update1 = new javax.swing.JButton();
        totalbooks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("BOOK ID :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("PRICE   :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("NAME      :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("AUTHOR  :");

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("ENGLISH NOVELS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(730, 730, 730))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        eid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidActionPerformed(evt);
            }
        });

        jTable_display_books.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable_display_books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BOOK ID", "NAME ", "AUHTOR", "PRICE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_display_books.setGridColor(new java.awt.Color(153, 153, 153));
        jTable_display_books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_display_booksMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_display_books);
        if (jTable_display_books.getColumnModel().getColumnCount() > 0) {
            jTable_display_books.getColumnModel().getColumn(0).setResizable(false);
            jTable_display_books.getColumnModel().getColumn(1).setResizable(false);
            jTable_display_books.getColumnModel().getColumn(2).setResizable(false);
            jTable_display_books.getColumnModel().getColumn(3).setResizable(false);
        }

        delete.setBackground(new java.awt.Color(204, 0, 0));
        delete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        totalprice.setBackground(new java.awt.Color(0, 0, 153));
        totalprice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalprice.setText("TOTAL VALUE OF BOOKS");
        totalprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalpriceActionPerformed(evt);
            }
        });

        update1.setBackground(new java.awt.Color(255, 153, 0));
        update1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        update1.setText("UPDATE");
        update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update1ActionPerformed(evt);
            }
        });

        totalbooks.setBackground(new java.awt.Color(204, 255, 0));
        totalbooks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalbooks.setText("Total No Of Books");
        totalbooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalbooksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ename, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eid, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eprice, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(totalprice, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 84, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(update1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1596, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(74, 74, 74)
                    .addComponent(totalbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1382, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 124, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(eid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ename, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(eauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(eprice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(totalprice, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(412, Short.MAX_VALUE)
                    .addComponent(update1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(333, 333, 333)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(512, Short.MAX_VALUE)
                    .addComponent(totalbooks, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(233, 233, 233)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eidActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

        String query = "DELETE FROM enovels where eid = "+eid.getText();
        
        executeQuery(query,"DELETED");
        eid.setText("");
        ename.setText("");
        eauthor.setText("");
        eprice.setText("");
        
        
    }//GEN-LAST:event_deleteActionPerformed

    private void jTable_display_booksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_display_booksMouseClicked

            int i = jTable_display_books.getSelectedRow();
            TableModel model = jTable_display_books.getModel();
            eid.setText(model.getValueAt(i,0).toString());
            ename.setText(model.getValueAt(i,1).toString());
            eauthor.setText(model.getValueAt(i,2).toString());
            
            eprice.setText(model.getValueAt(i,3).toString());
    }//GEN-LAST:event_jTable_display_booksMouseClicked

    private void totalpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalpriceActionPerformed

            JOptionPane.showMessageDialog(null,"Total price of books :"+calculateTotal());
    }//GEN-LAST:event_totalpriceActionPerformed

    private void update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update1ActionPerformed
        String name = ename.getText();
        String author = eauthor.getText();
        String price = eprice.getText();
        String id = eid.getText();
        //double price = eprice.getText();
        //double price= Double.parseDouble(eprice.getText());
        //int id = Integer.parseInt(eid.getText());
        
        String query = "update enovels set ename = '"+ name+ "',eauthor = '"+author+"',eprice = '"+price+"' where eid = "+id;
         executeQuery(query,"UPDATED");     
        eid.setText("");
        ename.setText("");
        eauthor.setText("");
        eprice.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_update1ActionPerformed

    private void totalbooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalbooksActionPerformed
            try {
                // TODO add your handling code here:

                JOptionPane.showMessageDialog(null,"Total Number of books"+engcountRows());
            } catch (SQLException ex) {
                Logger.getLogger(DisplayENGnovels.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_totalbooksActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayENGnovels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayENGnovels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayENGnovels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayENGnovels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayENGnovels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JTextField eauthor;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField ename;
    private javax.swing.JTextField eprice;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_display_books;
    private javax.swing.JButton totalbooks;
    private javax.swing.JButton totalprice;
    private javax.swing.JButton update1;
    // End of variables declaration//GEN-END:variables
}
